Repository Core-Craft/backend, pull requests merged in 2023-10, with the labels that each got.

#10 Modular
  app/api/V1/api.py
  app/api/V1/endpoints/login.py
  app/api/V1/endpoints/subscription.py
  app/api/V1/endpoints/user.py
  app/db/base.py
  app/models/base.py
  app/models/subscription.py
  app/models/user.py
  app/schemas/subscription.py
  app/schemas/user.py
  app/schemas/utils.py
Labels: bug, documentation, enhancement, good first issue

#12 Added hashing password feature for saving password in DB
  app/api/V1/endpoints/user.py
Labels: enhancement, good first issue

#16 BUGFIX: Fixed existing user with same email issue
  app/api/V1/endpoints/user.py
Labels: bug

#15 feature: Added user Login authentication API
  app/api/V1/endpoints/user.py
  app/schemas/user.py
Labels: enhancement

#27 updated code of conduct rules
  CODE_OF_CONDUCT.md
Labels: enhancement
